// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A movie/TV show recommendation AI agent that generates personalized recommendations based on user vibe input.
 *
 * - generateRecommendation - A function that handles the recommendation generation process.
 * - GenerateRecommendationInput - The input type for the generateRecommendation function.
 * - GenerateRecommendationOutput - The return type for the generateRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecommendationInputSchema = z.object({
  vibe: z.string().describe('The desired vibe or mood of the movie/TV show.'),
  movieData: z.string().describe('Movie and TV show data retrieved from vector database.'),
});

export type GenerateRecommendationInput = z.infer<typeof GenerateRecommendationInputSchema>;

const GenerateRecommendationOutputSchema = z.object({
  title: z.string().describe('The title of the recommended movie or TV show.'),
  description: z.string().describe('A brief description of the recommended movie or TV show.'),
  streamingAvailability: z.string().describe('Where the movie/TV show is available for streaming.'),
});

export type GenerateRecommendationOutput = z.infer<typeof GenerateRecommendationOutputSchema>;

export async function generateRecommendation(input: GenerateRecommendationInput): Promise<GenerateRecommendationOutput> {
  return generateRecommendationFlow(input);
}

const generateRecommendationPrompt = ai.definePrompt({
  name: 'generateRecommendationPrompt',
  input: {schema: GenerateRecommendationInputSchema},
  output: {schema: GenerateRecommendationOutputSchema},
  prompt: `You are a movie and TV show recommendation expert.

  Based on the user's desired vibe and the movie/TV show data provided, generate a personalized recommendation.

  Desired vibe: {{{vibe}}}
  Movie/TV show data: {{{movieData}}}

  Recommendation should include the title, description, and streaming availability.
  Make sure the output is properly formatted.
  `, 
});

const generateRecommendationFlow = ai.defineFlow(
  {
    name: 'generateRecommendationFlow',
    inputSchema: GenerateRecommendationInputSchema,
    outputSchema: GenerateRecommendationOutputSchema,
  },
  async input => {
    const {output} = await generateRecommendationPrompt(input);
    return output!;
  }
);
