
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A movie/TV show recommendation AI agent that generates personalized recommendations based on user vibe input.
 *
 * - generateRecommendation - A function that handles the recommendation generation process.
 * - GenerateRecommendationInput - The input type for the generateRecommendation function.
 * - GenerateRecommendationOutput - The return type for the generateRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecommendationInputSchema = z.object({
  vibe: z.string().describe('The desired vibe or mood of the movie/TV show.'),
});

export type GenerateRecommendationInput = z.infer<typeof GenerateRecommendationInputSchema>;

const SingleRecommendationSchema = z.object({
  title: z.string().describe('The title of the recommended movie or TV show.'),
  themes: z.array(z.string()).describe('A list of 2-3 main themes or keywords for the movie/TV show, like "dystopian", "coming-of-age", or "heist".'),
  description: z.string().describe('A brief description of the recommended movie or TV show.'),
  streamingAvailability: z.string().describe('Where the movie/TV show is available for streaming.'),
});

const GenerateRecommendationOutputSchema = z.array(SingleRecommendationSchema).describe("A list of 5 movie or TV show recommendations.");


export type GenerateRecommendationOutput = z.infer<typeof GenerateRecommendationOutputSchema>;

export async function generateRecommendation(input: GenerateRecommendationInput): Promise<GenerateRecommendationOutput> {
  return generateRecommendationFlow(input);
}

const generateRecommendationPrompt = ai.definePrompt({
  name: 'generateRecommendationPrompt',
  input: {schema: GenerateRecommendationInputSchema},
  output: {schema: GenerateRecommendationOutputSchema},
  prompt: `You are a movie and TV show recommendation expert.

  Based on the user's desired vibe, generate a list of 5 personalized recommendations.

  Desired vibe: {{{vibe}}}

  Each recommendation in the list should include the title, a list of 2-3 main themes, a description, and streaming availability.
  Make sure the output is a properly formatted array of 5 recommendations.
  `, 
});

const generateRecommendationFlow = ai.defineFlow(
  {
    name: 'generateRecommendationFlow',
    inputSchema: GenerateRecommendationInputSchema,
    outputSchema: GenerateRecommendationOutputSchema,
  },
  async input => {
    const {output} = await generateRecommendationPrompt(input);
    return output!;
  }
);
