// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Implements the Genkit flow for retrieving movie/TV show recommendations based on user preferences.
 *
 * - retrieveRecommendations - A function that retrieves movie/TV show recommendations based on user preferences.
 * - RetrieveRecommendationsInput - The input type for the retrieveRecommendations function.
 * - RetrieveRecommendationsOutput - The return type for the retrieveRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RetrieveRecommendationsInputSchema = z.object({
  preferences: z
    .string()
    .describe('User preferences regarding movie and TV shows.'),
});
export type RetrieveRecommendationsInput = z.infer<
  typeof RetrieveRecommendationsInputSchema
>;

const RetrieveRecommendationsOutputSchema = z.object({
  recommendation: z.string().describe('Movie/TV show recommendation.'),
});
export type RetrieveRecommendationsOutput = z.infer<
  typeof RetrieveRecommendationsOutputSchema
>;

export async function retrieveRecommendations(
  input: RetrieveRecommendationsInput
): Promise<RetrieveRecommendationsOutput> {
  return retrieveRecommendationsFlow(input);
}

const retrieveRecommendationsPrompt = ai.definePrompt({
  name: 'retrieveRecommendationsPrompt',
  input: {schema: RetrieveRecommendationsInputSchema},
  output: {schema: RetrieveRecommendationsOutputSchema},
  prompt: `Based on the following user preferences: """{{{preferences}}}""", retrieve movie/TV show recommendations.`,
});

const retrieveRecommendationsFlow = ai.defineFlow(
  {
    name: 'retrieveRecommendationsFlow',
    inputSchema: RetrieveRecommendationsInputSchema,
    outputSchema: RetrieveRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await retrieveRecommendationsPrompt(input);
    return output!;
  }
);
